services:
  medi-eco-book-stack-query-actions:
    image: fluxms/flux-eco-ehf-app-backend:v2022-03-25-1
    ports:
      - 127.1.2.8:8200:8200
    volumes:
      - ./../data:/opt/flux-eco-ehf-app-backend/app/data